version: "3.7"
services:
  caddy-gen:
    container_name: caddy2-gen
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoami
      - whoami2

  whoami:
    image: "katacoda/docker-http-server:v1"
    labels:
      virtual.host: test1.localhost
      # don't forget to set CSP
      virtual.proxy.directives: |
        header_down strict-transport-security "max-age=63072000; includeSubdomains; preload;"
        header_down x-content-type-options "nosniff"
        header_down x-frame-options "DENY"
        header_down x-xss-protection "1; mode=block"
        header_down referrer-policy "same-origin"
        header_down cross-origin-opener-policy "same-origin"

  whoami2:
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=test2.localhost"
